# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#


OrdererOrgs:

  - Name: Orderer
    Domain: example.com

    Specs:
      - Hostname: orderer

PeerOrgs:

  - Name: Org1
    Domain: org1.example.com
    Template:
      Count: 1 #피어 수
    Users:
      Count: 10 #user 수

  - Name: Org2
    Domain: org2.example.com
    Template:
      Count: 2 #피어 수
    Users:
      Count: 1 #user 수
  - Name: Org3
    Domain: org3.example.com
    Template:
      Count: 1 #피어 수
    Users:
      Count: 1 #user 수      