Organizations:

    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererOrg
        MSPDir: crypto-config/ordererOrganizations/knucoin.com/msp

    - &SalesOrg
        Name: SalesOrg
        ID: SalesOrg
        MSPDir: crypto-config/peerOrganizations/sales.knucoin.com/msp
        AnchorPeers:
            - Host: peer0.sales.knucoin.com
              Port: 7051

    - &CustomerOrg
        Name: CustomerOrg
        ID: CustomerOrg
        MSPDir: crypto-config/peerOrganizations/customer.knucoin.com/msp
        AnchorPeers:
            - Host: peer0.customer.knucoin.com
              Port: 7051

Orderer: &OrdererDefaults

    OrdererType: solo
    Addresses:
        - orderer.knucoin.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Kafka:
        Brokers:
            - 127.0.0.1:9092
    
    EtcdRaft:
        Consenters:
            - Host: orderer.knucoin.com
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/knucoin.com/orderers/orderer.knucoin.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/knucoin.com/orderers/orderer.knucoin.com/tls/server.crt
            - Host: orderer2.knucoin.com
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/knucoin.com/orderers/orderer2.knucoin.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/knucoin.com/orderers/orderer2.knucoin.com/tls/server.crt
            - Host: orderer3.knucoin.com
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/knucoin.com/orderers/orderer3.knucoin.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/knucoin.com/orderers/orderer3.knucoin.com/tls/server.crt
            - Host: orderer4.knucoin.com
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/knucoin.com/orderers/orderer4.knucoin.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/knucoin.com/orderers/orderer4.knucoin.com/tls/server.crt
            - Host: orderer5.knucoin.com
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/knucoin.com/orderers/orderer5.knucoin.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/knucoin.com/orderers/orderer5.knucoin.com/tls/server.crt

    Organizations:

Application: &ApplicationDefaults
    Organizations:
    
Profiles:

    OrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *SalesOrg
                    - *CustomerOrg
    Channel1:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *SalesOrg
                - *CustomerOrg
